/*
 * Segundo proyecto programado del curso de programación.
 * Universidad de Costa Rica - Sede del Pacífico Arnoldo Ferreto Segura
 */
package vista;

import controlador.Controlador_FRM_VentanaPuntajes;

/**
 *
 * @author JorgeIgnacio
 */
public class FRM_VentanaPuntajes extends javax.swing.JFrame {

    //Referencias de clase
    Controlador_FRM_VentanaPuntajes controlador_FRM_VentanaPuntajes;
    FRM_VentanaInicio fRM_VentanaInicio;
    
    //Constructor de la clase
    public FRM_VentanaPuntajes(FRM_VentanaInicio fRM_VentanaInicio) {
        initComponents();
        this.fRM_VentanaInicio = fRM_VentanaInicio;
        controlador_FRM_VentanaPuntajes = new Controlador_FRM_VentanaPuntajes(this, fRM_VentanaInicio);
        
        this.jB_Atras.addActionListener(controlador_FRM_VentanaPuntajes);
        
        this.setLocation(200, 10);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_Atras = new javax.swing.JButton();
        jLabel_FondoPuntajes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(980, 680));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_Atras.setText("Atrás");
        jB_Atras.setActionCommand("Atras");
        getContentPane().add(jB_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, -1, -1));

        jLabel_FondoPuntajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo-juego.png"))); // NOI18N
        getContentPane().add(jLabel_FondoPuntajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Atras;
    private javax.swing.JLabel jLabel_FondoPuntajes;
    // End of variables declaration//GEN-END:variables
}
