/*
 * Segundo proyecto programado del curso de programación.
 * Universidad de Costa Rica - Sede del Pacífico Arnoldo Ferreto Segura
 */
package vista;

import controlador.Controlador_FRM_RegistroJugador;

/**
 *
 * @author JorgeIgnacio
 */
public class FRM_RegistroJugador extends javax.swing.JFrame {

    //Referencias de clases
    Controlador_FRM_RegistroJugador cfrmrj;
    
    public FRM_RegistroJugador() {
        initComponents();
        
        this.setLocation(200, 10);
              
        //Instancias de clases
        cfrmrj = new Controlador_FRM_RegistroJugador(this);
        this.jB_GuardarRegistroJugador.addActionListener(cfrmrj);
        
    }
    
    public String[] extraerDatos() {
        
        String var[] = new String[2];
        
        var[0] = this.jT_NombreRegistroJugador.getText();
        var[1] = this.jT_RecordRegistroJugador.getText();
        
        return var;        
    }
    
    public void limpiarCampos() {
        
        this.jT_NombreRegistroJugador.setText("");
        this.jT_RecordRegistroJugador.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jB_GuardarRegistroJugador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jT_NombreRegistroJugador = new javax.swing.JTextField();
        jT_RecordRegistroJugador = new javax.swing.JTextField();
        jL_FondoRegistroJugador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(980, 680));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Impact", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 230, 170, 70);

        jB_GuardarRegistroJugador.setBackground(new java.awt.Color(102, 102, 102));
        jB_GuardarRegistroJugador.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        jB_GuardarRegistroJugador.setForeground(new java.awt.Color(0, 204, 204));
        jB_GuardarRegistroJugador.setText("GUARDAR");
        jB_GuardarRegistroJugador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        getContentPane().add(jB_GuardarRegistroJugador);
        jB_GuardarRegistroJugador.setBounds(750, 560, 160, 70);

        jLabel2.setFont(new java.awt.Font("Impact", 2, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("RECORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(600, 240, 160, 50);

        jT_NombreRegistroJugador.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        jT_NombreRegistroJugador.setForeground(new java.awt.Color(0, 255, 255));
        getContentPane().add(jT_NombreRegistroJugador);
        jT_NombreRegistroJugador.setBounds(230, 240, 340, 50);

        jT_RecordRegistroJugador.setFont(new java.awt.Font("Impact", 2, 48)); // NOI18N
        jT_RecordRegistroJugador.setForeground(new java.awt.Color(0, 255, 255));
        getContentPane().add(jT_RecordRegistroJugador);
        jT_RecordRegistroJugador.setBounds(790, 240, 150, 50);

        jL_FondoRegistroJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo-juego.png"))); // NOI18N
        getContentPane().add(jL_FondoRegistroJugador);
        jL_FondoRegistroJugador.setBounds(0, 0, 980, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_GuardarRegistroJugador;
    private javax.swing.JLabel jL_FondoRegistroJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jT_NombreRegistroJugador;
    private javax.swing.JTextField jT_RecordRegistroJugador;
    // End of variables declaration//GEN-END:variables
}
