/*
 * Segundo proyecto programado del curso de programación.
 * Universidad de Costa Rica - Sede del Pacífico Arnoldo Ferreto Segura
 */
package vista;

import controlador.Controlador_FRM_VentanaInicio;
//import modelo.Jugador_XML;
/**
 *
 * @author JorgeIgnacio
 */
public class FRM_VentanaPuntajes extends javax.swing.JFrame {

    //Referencias de clase
//    Jugador_XML jugador_XML;
    FRM_VentanaInicio fRM_VentanaInicio;
    
    //Constructor de la clase
    public FRM_VentanaPuntajes(/*Jugador_XML jugador_XML*/) {
        initComponents();
        
        this.setLocation(200, 10);
//        this.jugador_XML = jugador_XML;
        
    }
    
    public void mostrarPuntaje() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_Atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel_FondoPuntajes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_Atras.setBackground(new java.awt.Color(102, 102, 102));
        jB_Atras.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        jB_Atras.setForeground(new java.awt.Color(204, 204, 204));
        jB_Atras.setText("Atrás");
        jB_Atras.setActionCommand("Atras");
        jB_Atras.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(255, 0, 255), new java.awt.Color(255, 0, 255)));
        getContentPane().add(jB_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 560, 170, 70));

        jLabel1.setFont(new java.awt.Font("Impact", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 170, 50));

        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 340, 50));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(102, 102, 102));
        jTextField2.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setOpaque(false);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 160, 120));

        jLabel_FondoPuntajes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo-juego.png"))); // NOI18N
        getContentPane().add(jLabel_FondoPuntajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jB_Atras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_FondoPuntajes;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
