/*
 * Segundo proyecto programado del curso de programación.
 * Universidad de Costa Rica - Sede del Pacífico Arnoldo Ferreto Segura
 */
package vista;

import controlador.Controlador_FRM_VentanaInicio;
/**
 *
 * @author JorgeIgnacio
 */
public class FRM_VentanaInicio extends javax.swing.JFrame {

    //Referencias de clase
    Controlador_FRM_VentanaInicio controlador_FRM_VentanaInicio;
    FRM_VentanaJuego fRM_VentanaJuego;
    FRM_VentanaPuntajes fRM_VentanaPuntajes;
    FRM_VentanaCreditos fRM_VentanaCreditos;
    
    public FRM_VentanaInicio() {
        initComponents();
        
        //Instancias de clase
        fRM_VentanaJuego = new FRM_VentanaJuego();
        fRM_VentanaPuntajes = new FRM_VentanaPuntajes(this);
        fRM_VentanaCreditos = new FRM_VentanaCreditos(this);
        
        controlador_FRM_VentanaInicio = new Controlador_FRM_VentanaInicio(this, fRM_VentanaJuego, fRM_VentanaPuntajes, fRM_VentanaCreditos);
        
        this.setLocation(200, 10);
        agregarEventos(controlador_FRM_VentanaInicio);
        
    }
    
    
    public void agregarEventos(Controlador_FRM_VentanaInicio controlador_FRM_VentanaInicio) {
        
        this.controlador_FRM_VentanaInicio = controlador_FRM_VentanaInicio;
        
        this.jB_Jugar.addActionListener(controlador_FRM_VentanaInicio);
        this.jB_Puntajes.addActionListener(controlador_FRM_VentanaInicio);
        this.jB_Creditos.addActionListener(controlador_FRM_VentanaInicio);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_Jugar = new javax.swing.JButton();
        jB_Puntajes = new javax.swing.JButton();
        jB_Creditos = new javax.swing.JButton();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(980, 680));
        setResizable(false);
        getContentPane().setLayout(null);

        jB_Jugar.setText("Jugar");
        getContentPane().add(jB_Jugar);
        jB_Jugar.setBounds(510, 180, 120, 26);

        jB_Puntajes.setText("Puntajes");
        getContentPane().add(jB_Puntajes);
        jB_Puntajes.setBounds(510, 220, 120, 26);

        jB_Creditos.setText("Créditos");
        jB_Creditos.setActionCommand("Creditos");
        getContentPane().add(jB_Creditos);
        jB_Creditos.setBounds(510, 260, 120, 26);

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo-juego.png"))); // NOI18N
        getContentPane().add(jLabel_Fondo);
        jLabel_Fondo.setBounds(0, 0, 980, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FRM_VentanaJuego().setVisible(true);
                  new FRM_VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Creditos;
    private javax.swing.JButton jB_Jugar;
    private javax.swing.JButton jB_Puntajes;
    private javax.swing.JLabel jLabel_Fondo;
    // End of variables declaration//GEN-END:variables
}
