/*
 * Segundo proyecto programado del curso de programación.
 * Universidad de Costa Rica - Sede del Pacífico Arnoldo Ferreto Segura
 */
package vista;

import modelo.HiloCreditos;

/**
 *
 * @author JorgeIgnacio
 */
public class FRM_VentanaCreditos extends javax.swing.JFrame {

    //Referencia de clases
    FRM_VentanaInicio fRM_VentanaInicio;
    HiloCreditos hiloCreditos;
    
    public FRM_VentanaCreditos(FRM_VentanaInicio fRM_VentanaInicio) {
        initComponents();
        
        //Instancias de clase
        this.fRM_VentanaInicio = fRM_VentanaInicio;
        hiloCreditos = new HiloCreditos(this);
        this.setLocation(200, 10);
        
    }
    
    public void moverFondo() {
        if(jL_Creditos.getY()<-250)
        {
            jL_Creditos.setLocation(jL_Creditos.getX(),jL_Creditos.getY()-15);
        }
        else
        {
            jL_Creditos.setLocation(jL_Creditos.getX(), -1000);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Creditos = new javax.swing.JLabel();
        jL_VentanaCreditos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(980, 680));
        setResizable(false);
        getContentPane().setLayout(null);

        jL_Creditos.setForeground(new java.awt.Color(0, 255, 255));
        jL_Creditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/creditos.png"))); // NOI18N
        getContentPane().add(jL_Creditos);
        jL_Creditos.setBounds(0, -300, 980, 2100);

        jL_VentanaCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo-juego.png"))); // NOI18N
        jL_VentanaCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jL_VentanaCreditosMouseClicked(evt);
            }
        });
        getContentPane().add(jL_VentanaCreditos);
        jL_VentanaCreditos.setBounds(0, -20, 990, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jL_VentanaCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jL_VentanaCreditosMouseClicked

        this.setVisible(false);
        this.fRM_VentanaInicio.setVisible(true);
        
    }//GEN-LAST:event_jL_VentanaCreditosMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jL_Creditos;
    private javax.swing.JLabel jL_VentanaCreditos;
    // End of variables declaration//GEN-END:variables
}
