/*
 * Segundo proyecto programado del curso de programación.
 * Universidad de Costa Rica - Sede del Pacífico Arnoldo Ferreto Segura
 */
package vista;

import controlador.Controlador_FRM_VentanaInicio;
import vista.FRM_RegistroJugador;
//import modelo.Jugador_XML;
/**
 *
 * @author JorgeIgnacio
 */
public class FRM_VentanaInicio extends javax.swing.JFrame {

    //Referencias de clase
    Controlador_FRM_VentanaInicio controlador_FRM_VentanaInicio;
    FRM_VentanaJuego fRM_VentanaJuego;
    FRM_VentanaPuntajes fRM_VentanaPuntajes;
    FRM_VentanaCreditos fRM_VentanaCreditos;
    FRM_RegistroJugador fRM_RegistroJugador;
//    Jugador_XML jugador_XML;
    
    public FRM_VentanaInicio() {
        initComponents();
        
        //Instancias de clase
//        jugador_XML = new Jugador_XML();
        fRM_RegistroJugador = new FRM_RegistroJugador();
        fRM_VentanaJuego = new FRM_VentanaJuego(this, fRM_RegistroJugador);
        fRM_VentanaPuntajes = new FRM_VentanaPuntajes(/*jugador_XML*/);
        fRM_VentanaCreditos = new FRM_VentanaCreditos(this);
        
        
        controlador_FRM_VentanaInicio = new Controlador_FRM_VentanaInicio(this, fRM_VentanaJuego, fRM_VentanaPuntajes, fRM_VentanaCreditos, fRM_RegistroJugador/*, jugador_XML*/);
        
        this.setLocation(200, 10);
        
        agregarEventos(controlador_FRM_VentanaInicio);
        
        this.fRM_RegistroJugador.jB_GuardarRegistroJugador.addActionListener(controlador_FRM_VentanaInicio);
        this.fRM_VentanaPuntajes.jB_Atras.addActionListener(controlador_FRM_VentanaInicio);
        
    }
    
    public void manejoDeVentanas() {
        this.fRM_VentanaPuntajes.setVisible(false);
        this.setVisible(true);
    }
    
    public void agregarEventos(Controlador_FRM_VentanaInicio controlador_FRM_VentanaInicio) {
        
        this.controlador_FRM_VentanaInicio = controlador_FRM_VentanaInicio;
        
        this.jB_Jugar.addActionListener(controlador_FRM_VentanaInicio);
        this.jB_Puntajes.addActionListener(controlador_FRM_VentanaInicio);
        this.jB_Creditos.addActionListener(controlador_FRM_VentanaInicio);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_Jugar = new javax.swing.JButton();
        jB_Puntajes = new javax.swing.JButton();
        jB_Creditos = new javax.swing.JButton();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_Jugar.setBackground(new java.awt.Color(102, 102, 102));
        jB_Jugar.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        jB_Jugar.setForeground(new java.awt.Color(204, 204, 204));
        jB_Jugar.setText("Jugar");
        jB_Jugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(255, 0, 255), new java.awt.Color(255, 0, 255)));
        jB_Jugar.setFocusPainted(false);
        jB_Jugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jB_JugarKeyPressed(evt);
            }
        });
        getContentPane().add(jB_Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 160, 70));

        jB_Puntajes.setBackground(new java.awt.Color(102, 102, 102));
        jB_Puntajes.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        jB_Puntajes.setForeground(new java.awt.Color(204, 204, 204));
        jB_Puntajes.setText("Puntajes");
        jB_Puntajes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(255, 0, 255), new java.awt.Color(255, 0, 255)));
        jB_Puntajes.setFocusPainted(false);
        jB_Puntajes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jB_PuntajesKeyPressed(evt);
            }
        });
        getContentPane().add(jB_Puntajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 160, 70));

        jB_Creditos.setBackground(new java.awt.Color(102, 102, 102));
        jB_Creditos.setFont(new java.awt.Font("Impact", 2, 24)); // NOI18N
        jB_Creditos.setForeground(new java.awt.Color(204, 204, 204));
        jB_Creditos.setText("Créditos");
        jB_Creditos.setActionCommand("Creditos");
        jB_Creditos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(255, 0, 255), new java.awt.Color(255, 0, 255)));
        jB_Creditos.setFocusPainted(false);
        jB_Creditos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jB_CreditosKeyPressed(evt);
            }
        });
        getContentPane().add(jB_Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 160, 70));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo-juego.png"))); // NOI18N
        getContentPane().add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_JugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jB_JugarKeyPressed
       
        if(evt.getKeyCode() == 10) {
            
            controlador_FRM_VentanaInicio.jugarRapido();
            
        }
        
    }//GEN-LAST:event_jB_JugarKeyPressed

    private void jB_PuntajesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jB_PuntajesKeyPressed
      
        if(evt.getKeyCode() == 10) {
            controlador_FRM_VentanaInicio.puntajesRapido();
        }
        
    }//GEN-LAST:event_jB_PuntajesKeyPressed

    private void jB_CreditosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jB_CreditosKeyPressed
        
        if(evt.getKeyCode() == 10) {
            controlador_FRM_VentanaInicio.creditosRapido();
        }
        
    }//GEN-LAST:event_jB_CreditosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  new FRM_VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Creditos;
    private javax.swing.JButton jB_Jugar;
    private javax.swing.JButton jB_Puntajes;
    private javax.swing.JLabel jLabel_Fondo;
    // End of variables declaration//GEN-END:variables
}
