/*
 * Segundo proyecto programado del curso de programación.
 * Universidad de Costa Rica - Sede del Pacífico Arnoldo Ferreto Segura
 */
package vista;
import modelo.Hilo;
import modelo.MetodosPersonaje;
import modelo.MetodosEnemigo;


/**
 *
 * @author tecnologiamultimedia
 */
public class Ventana extends javax.swing.JFrame {

    //Referencias de la clase
    Hilo hilo;
    MetodosPersonaje metodosPersonaje;
    MetodosEnemigo metodosEnemigo;
    
    //Se declaran las variables
    public String estado = "EnELSuelo";
    private boolean presionado = false;
    
    
    //Constructor de la clase
    public Ventana() {
        initComponents();
        
        this.setLocation(500, 100);
        
        //Instancias de la clase
        metodosPersonaje = new MetodosPersonaje(this);
        metodosEnemigo = new MetodosEnemigo(this);
        hilo=new Hilo(this, metodosPersonaje, metodosEnemigo);
        hilo.start();      
        
    }
    
    /**
     * Método que posiciona la imagen de fondo en su posición inicial obteniendo
     * la posición en -y-. Si el valor de la imagen en -y- es menor que -50y lo de
     * vuvuelve a su ligar inicial.
     */
    public void moverFondo()
    {
        if(jl_Fondo.getY()<-50)
        {
            jl_Fondo.setLocation(jl_Fondo.getX(),jl_Fondo.getY()+20);
        }
        else
        {
            jl_Fondo.setLocation(jl_Fondo.getX(), -500);
        }
    }
    
    /**
     * Método que verica si el personaje se ha encontrado con el obstáculo en la
     * pantalla.
     */
    public boolean verificarObstaculo() {
        
        boolean colision = false;
        if(jL_Personaje.getY()-80<jL_naveEnemigo.getY() && jL_Personaje.getX()==jL_naveEnemigo.getX() && jL_naveEnemigo.getX()+130>jL_Personaje.getX()) {
            colision = true;
        }
        
        return colision;
    
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_Personaje = new javax.swing.JLabel();
        jL_naveEnemigo = new javax.swing.JLabel();
        jl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_Personaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nave.png"))); // NOI18N
        jL_Personaje.setPreferredSize(new java.awt.Dimension(130, 105));
        getContentPane().add(jL_Personaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 140, 110));

        jL_naveEnemigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/naveEnemigo.png"))); // NOI18N
        getContentPane().add(jL_naveEnemigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoFinal.png"))); // NOI18N
        getContentPane().add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -500, 400, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        if(evt.getKeyCode() == 37 ) {
            
            estado = "izquierda";
            
        }
        if(evt.getKeyCode() == 39) {
            
            estado = "derecha";
            
        }
        if(evt.getKeyCode() == 38) {
            
            estado = "arriba";
            
        }
        if(evt.getKeyCode() == 40) {
            
            estado = "abajo";
            
        }
        
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

        if(evt.getKeyCode() == 37 ) {
            
            estado = "EnElSuelo";
            
        }
        if(evt.getKeyCode() == 39) {
            
            estado = "EnElSuelo";
            
        }
        if(evt.getKeyCode() == 38) {
            
            estado = "EnElSuelo";
            
        }
        if(evt.getKeyCode() == 40) {
            
            estado = "EnELSuelo";
            
        }
        
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jL_Personaje;
    public javax.swing.JLabel jL_naveEnemigo;
    private javax.swing.JLabel jl_Fondo;
    // End of variables declaration//GEN-END:variables


}//Fin de la clase Ventana
